allianceauth/groupmanagement/urls.py
from . import views

from django.conf.urls import url

app_name = "groupmanagement"

urlpatterns = [
    # groups
    url(r"^groups/$", views.groups_view, name="groups"),
    url(r"^group/request/join/(\w+)/$", views.group_request_add, name="request_add"),
    url(
        r"^group/request/leave/(\w+)/$", views.group_request_leave, name="request_leave"
    ),
    # group management
    url(r"^groupmanagement/requests/$", views.group_management, name="management"),
    url(r"^groupmanagement/membership/$", views.group_membership, name="membership"),
    url(
        r"^groupmanagement/membership/(\w+)/$",
        views.group_membership_list,
        name="membership",
    ),
    url(
        r"^groupmanagement/membership/(\w+)/audit-log/$",
        views.group_membership_audit,
        name="audit_log",
    ),
    url(
        r"^groupmanagement/membership/(\w+)/remove/(\w+)/$",
        views.group_membership_remove,
        name="membership_remove",
    ),
    url(
        r"^groupmanagement/request/join/accept/(\w+)/$",
        views.group_accept_request,
        name="accept_request",
    ),
    url(
        r"^groupmanagement/request/join/reject/(\w+)/$",
        views.group_reject_request,
        name="reject_request",
    ),
    url(
        r"^groupmanagement/request/leave/accept/(\w+)/$",
        views.group_leave_accept_request,
        name="leave_accept_request",
    ),
    url(
        r"^groupmanagement/request/leave/reject/(\w+)/$",
        views.group_leave_reject_request,
        name="leave_reject_request",
    ),
]

allianceauth/urls.py
import esi.urls

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication
    url(r'', include(allianceauth.authentication.urls)),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    url(r'^account/', include(hmac_urls)),

    # Admin urls
    url(r'^admin/', admin.site.urls),

    # SSO
    url(r'^sso/', include((esi.urls, 'esi'), namespace='esi')),
    url(r'^sso/login$', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    url(r'', include(allianceauth.notifications.urls)),

    # Groups
    url(r'', include(allianceauth.groupmanagement.urls)),

    # Services
    url(r'', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    url(r'^night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [url(r'', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/groupmanagement/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Count
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from allianceauth.notifications import notify

from .managers import GroupManager
from .models import GroupRequest, RequestLog


logger = logging.getLogger(__name__)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_management(request):
    logger.debug("group_management called by user %s" % request.user)
    acceptrequests = []
    leaverequests = []

    base_group_query = GroupRequest.objects.select_related('user', 'group', 'user__profile__main_character')
    if GroupManager.has_management_permission(request.user):
        # Full access
        group_requests = base_group_query.all()
    else:
        # Group specific leader
        users__groups = GroupManager.get_group_leaders_groups(request.user)
        group_requests = base_group_query.filter(group__in=users__groups)

    for grouprequest in group_requests:
        if grouprequest.leave_request:
            leaverequests.append(grouprequest)
        else:
            acceptrequests.append(grouprequest)

    logger.debug("Providing user {} with {} acceptrequests and {} leaverequests.".format(
        request.user, len(acceptrequests), len(leaverequests)))

    render_items = {
        'acceptrequests': acceptrequests,
        'leaverequests': leaverequests,
        'auto_leave': getattr(settings, 'GROUPMANAGEMENT_AUTO_LEAVE', False),
    }

    return render(request, 'groupmanagement/index.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership(request):
    logger.debug("group_membership called by user %s" % request.user)
    # Get all open and closed groups
    if GroupManager.has_management_permission(request.user):
        # Full access
        groups = GroupManager.get_all_non_internal_groups()
    else:
        # Group leader specific
        groups = GroupManager.get_group_leaders_groups(request.user)

    groups = groups.exclude(authgroup__internal=True).annotate(num_members=Count('user')).order_by('name')

    render_items = {'groups': groups}

    return render(request, 'groupmanagement/groupmembership.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_audit(request, group_id):
    logger.debug("group_management_audit called by user %s" % request.user)
    group = get_object_or_404(Group, id=group_id)
    try:
        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if not GroupManager.check_internal_group(group) or not GroupManager.can_manage_group(request.user, group):
            logger.warning(f"User {request.user} attempted to view the membership of group {group_id} but permission was denied")
            raise PermissionDenied

    except ObjectDoesNotExist:
        raise Http404("Group does not exist")
    render_items = {'group': group.name}
    entries = RequestLog.objects.filter(group=group).order_by('-date')
    render_items['entries'] = entries

    return render(request, 'groupmanagement/audit.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_list(request, group_id):
    logger.debug(
        "group_membership_list called by user %s "
        "for group id %s" % (request.user, group_id)
    )
    group = get_object_or_404(Group, id=group_id)
    try:

        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if (not GroupManager.check_internal_group(group)
            or not GroupManager.can_manage_group(request.user, group)
        ):
            logger.warning(
                "User %s attempted to view the membership of group %s "
                "but permission was denied" % (request.user, group_id)
            )
            raise PermissionDenied

    except ObjectDoesNotExist:
        raise Http404("Group does not exist")

    group_leaders = group.authgroup.group_leaders.all()
    members = list()
    for member in \
        group.user_set\
            .all()\
            .select_related('profile', 'profile__main_character')\
            .order_by('profile__main_character__character_name'):

        members.append({
            'user': member,
            'main_char': member.profile.main_character,
            'is_leader': member in group_leaders
        })

    render_items = {'group': group, 'members': members}

    return render(
        request, 'groupmanagement/groupmembers.html',
        context=render_items
    )


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_remove(request, group_id, user_id):
    logger.debug(f"group_membership_remove called by user {request.user} for group id {group_id} on user id {user_id}")
    group = get_object_or_404(Group, id=group_id)
    try:
        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if not GroupManager.check_internal_group(group) or not GroupManager.can_manage_group(request.user, group):
            logger.warning(f"User {request.user} attempted to remove a user from group {group_id} but permission was denied")
            raise PermissionDenied

        try:
            user = group.user_set.get(id=user_id)
            request_info = user.username + ":" + group.name
            log = RequestLog(request_type=None,group=group,request_info=request_info,action=1,request_actor=request.user)
            log.save()
            # Remove group from user
            user.groups.remove(group)
            logger.info(f"User {request.user} removed user {user} from group {group}")
            messages.success(request, _("Removed user %(user)s from group %(group)s.") % {"user": user, "group": group})
        except ObjectDoesNotExist:
            messages.warning(request, _("User does not exist in that group"))

    except ObjectDoesNotExist:
        messages.warning(request, _("Group does not exist"))

    return redirect('groupmanagement:membership', group_id)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_accept_request(request, group_request_id):
    logger.debug(f"group_accept_request called by user {request.user} for grouprequest id {group_request_id}")
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        group, created = Group.objects.get_or_create(name=group_request.group.name)

        if not GroupManager.joinable_group(group_request.group, group_request.user.profile.state) or \
                not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        group_request.user.groups.add(group)
        group_request.user.save()
        log = RequestLog(request_type=group_request.leave_request,group=group,request_info=group_request.__str__(),action=1,request_actor=request.user)
        log.save()
        group_request.delete()
        logger.info("User {} accepted group request from user {} to group {}".format(
            request.user, group_request.user, group_request.group.name))
        notify(group_request.user, "Group Application Accepted", level="success",
                message="Your application to %s has been accepted." % group_request.group)
        messages.success(request,
                        _('Accepted application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})

    except PermissionDenied as p:
        logger.warning(f"User {request.user} attempted to accept group join request {group_request_id} but permission was denied")
        raise p
    except:
        messages.error(request, _('An unhandled error occurred while processing the application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})
        logger.exception("Unhandled exception occurred while user {} attempting to accept grouprequest id {}.".format(
            request.user, group_request_id))
        pass

    return redirect("groupmanagement:management")


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_reject_request(request, group_request_id):
    logger.debug(f"group_reject_request called by user {request.user} for group request id {group_request_id}")
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        if not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        if group_request:
            logger.info("User {} rejected group request from user {} to group {}".format(
                request.user, group_request.user, group_request.group.name))
            log = RequestLog(request_type=group_request.leave_request,group=group_request.group,request_info=group_request.__str__(),action=0,request_actor=request.user)
            log.save()
            group_request.delete()
            notify(group_request.user, "Group Application Rejected", level="danger", message="Your application to %s has been rejected." % group_request.group)
            messages.success(request,
                            _('Rejected application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})

    except PermissionDenied as p:
        logger.warning(f"User {request.user} attempted to reject group join request {group_request_id} but permission was denied")
        raise p

allianceauth/groupmanagement/templates/groupmanagement/groupmembership.html
{% extends "allianceauth/base.html" %}
{% load static %}
{% load i18n %}

{% block page_title %}{% translate "Groups Membership" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'groupmanagement/menu.html' %}

        <div class="panel panel-default">
            <div class="panel-heading">
                {% translate "Groups" %}
            </div>

            <div class="panel-body">
                {% if groups %}
                    <div class="table-responsive">
                        <table class="table table-aa">
                            <thead>
                                <tr>
                                    <th>{% translate "Name" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th>{% translate "Status" %}</th>
                                    <th style="white-space: nowrap;">{% translate "Member Count" %}</th>
                                    <th style="min-width: 170px;"></th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for group in groups %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'groupmanagement:membership' group.id %}">{{ group.name }}</a>
                                        </td>

                                        <td>{{ group.authgroup.description|linebreaks|urlize }}</td>

                                        <td>
                                            {% if group.authgroup.hidden %}
                                                <span class="label label-info">{% translate "Hidden" %}</span>
                                            {% elif group.authgroup.open %}
                                                <span class="label label-success">{% translate "Open" %}</span>
                                            {% else %}
                                                <span class="label label-default">{% translate "Requestable" %}</span>
                                            {% endif %}
                                        </td>

                                        <td class="text-right">
                                            {{ group.num_members }}
                                        </td>

                                        <td class="text-right">
                                            <a href="{% url 'groupmanagement:membership' group.id %}" class="btn btn-primary" title="{% translate "View Members" %}">
                                                <i class="glyphicon glyphicon-eye-open"></i>
                                            </a>

                                            <a href="{% url "groupmanagement:audit_log" group.id %}" class="btn btn-info" title="{% translate "Audit Members" %}">
                                                <i class="glyphicon glyphicon-list-alt"></i>
                                            </a>

                                            <a id="clipboard-copy" data-clipboard-text="{{ request.scheme }}://{{request.get_host}}{% url 'groupmanagement:request_add' group.id %}" class="btn btn-warning" title="{% translate "Copy Direct Join Link" %}">
                                                <i class="glyphicon glyphicon-copy"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="alert alert-warning text-center">
                        {% translate "No groups to list." %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/clipboard-js.html' %}

    <script>
        new ClipboardJS('#clipboard-copy');
    </script>
{% endblock %}

allianceauth/groupmanagement/templates/groupmanagement/groups.html
{% extends "allianceauth/base.html" %}
{% load static %}
{% load i18n %}

{% block page_title %}{% translate "Available Groups" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% translate "Available Groups" %}</h1>
        {% if groups %}
            <table class="table table-aa">
                <thead>
                    <tr>
                        <th>{% translate "Name" %}</th>
                        <th>{% translate "Description" %}</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    {% for g in groups %}
                        <tr>
                            <td>{{ g.group.name }}</td>
                            <td>{{ g.group.authgroup.description|linebreaks|urlize }}</td>
                            <td class="text-right">
                                {% if g.group in user.groups.all %}
                                    {% if not g.request %}
                                        <a href="{% url 'groupmanagement:request_leave' g.group.id %}" class="btn btn-danger">
                                            {% translate "Leave" %}
                                        </a>
                                    {% else %}
                                        <button type="button" class="btn btn-primary" disabled>
                                            {% translate "Pending" %}
                                        </button>
                                    {% endif %}
                                {% elif not g.request %}
                                    {% if g.group.authgroup.open %}
                                        <a href="{% url 'groupmanagement:request_add' g.group.id %}" class="btn btn-success">
                                            {% translate "Join" %}
                                        </a>
                                    {% else %}
                                        <a href="{% url 'groupmanagement:request_add' g.group.id %}" class="btn btn-primary">
                                            {% translate "Request" %}
                                        </a>
                                    {% endif %}
                                {% else %}
                                    <button type="button" class="btn btn-primary" disabled>
                                        {% translate "Pending" %}
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-warning text-center">
                {% translate "No groups available." %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/index.html
{% extends "allianceauth/base.html" %}
{% load static %}
{% load i18n %}
{% load evelinks %}

{% block page_title %}{% translate "Groups Management" %}{% endblock page_title %}

{% block extra_css %}
    <style>
        .nav-tabs > li.active > a {
            background-color: rgb(236, 240, 241) !important;
            color: rgb(44, 62, 80);
        }
    </style>
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'groupmanagement/menu.html' %}

        <ul class="nav nav-tabs">
            <li class="active">
                <a data-toggle="tab" href="#add">
                    {% translate "Join Requests" %}

                    {% if acceptrequests %}
                        <span class="badge">{{ acceptrequests|length }}</span>
                    {% endif %}
                </a>
            </li>

            {%  if not auto_leave %}
                <li>
                    <a data-toggle="tab" href="#leave">
                        {% translate "Leave Requests" %}

                        {% if leaverequests %}
                            <span class="badge">{{ leaverequests|length }}</span>
                        {% endif %}
                    </a>
                </li>
            {% endif %}
        </ul>

        <div class="panel panel-default panel-tabs-aa">
            <div class="panel-body">
                <div class="tab-content">

                    <div id="add" class="tab-pane active">
                        {% if acceptrequests %}
                            <div class="table-responsive">
                                <table class="table table-aa">
                                    <thead>
                                        <tr>
                                            <th>{% translate "Character" %}</th>
                                            <th>{% translate "Organization" %}</th>
                                            <th>{% translate "Group" %}</th>
                                            <th></th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        {% for acceptrequest in acceptrequests %}
                                            <tr>
                                                <td>
                                                    <img src="{{ acceptrequest.main_char|character_portrait_url:32 }}" class="img-circle" style="margin-right: 1rem;">
                                                    {% if acceptrequest.main_char %}
                                                        <a href="{{ acceptrequest.main_char|evewho_character_url }}" target="_blank">
                                                            {{ acceptrequest.main_char.character_name }}
                                                        </a>
                                                    {% else %}
                                                        {{ acceptrequest.user.username }}
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    {% if acceptrequest.main_char %}
                                                        <a href="{{ acceptrequest.main_char|dotlan_corporation_url }}" target="_blank">
                                                            {{ acceptrequest.main_char.corporation_name }}
                                                        </a><br>
                                                        {{ acceptrequest.main_char.alliance_name|default_if_none:"" }}
                                                    {% else %}
                                                        {% translate "(unknown)" %}
                                                    {% endif %}
                                                </td>
                                                <td>{{ acceptrequest.group.name }}</td>
                                                <td class="text-right">
                                                    <a href="{% url 'groupmanagement:accept_request' acceptrequest.id %}" class="btn btn-success">
                                                        {% translate "Accept" %}
                                                    </a>

                                                    <a href="{% url 'groupmanagement:reject_request' acceptrequest.id %}" class="btn btn-danger">
                                                        {% translate "Reject" %}
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% else %}
                            <div class="alert alert-warning text-center">{% translate "No group add requests." %}</div>
                        {% endif %}
                    </div>

                    {%  if not auto_leave %}
                        <div id="leave" class="tab-pane">
                            {% if leaverequests %}
                                <div class="table-responsive">
                                    <table class="table table-aa">
                                        <thead>
                                            <tr>
                                                <th>{% translate "Character" %}</th>
                                                <th>{% translate "Organization" %}</th>
                                                <th>{% translate "Group" %}</th>
                                                <th></th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            {% for leaverequest in leaverequests %}
                                                <tr>
                                                    <td>
                                                        <img src="{{ leaverequest.main_char|character_portrait_url:32 }}" class="img-circle" style="margin-right: 1rem;">
                                                        {% if leaverequest.main_char %}
                                                            <a href="{{ leaverequest.main_char|evewho_character_url }}" target="_blank">
                                                                {{ leaverequest.main_char.character_name }}
                                                            </a>
                                                        {% else %}
                                                            {{ leaverequest.user.username }}
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if leaverequest.main_char %}
                                                            <a href="{{ leaverequest.main_char|dotlan_corporation_url }}" target="_blank">
                                                                {{ leaverequest.main_char.corporation_name }}
                                                            </a><br>
                                                            {{ leaverequest.main_char.alliance_name|default_if_none:"" }}
                                                        {% else %}
                                                            {% translate "(unknown)" %}
                                                        {% endif %}
                                                    </td>
                                                    <td>{{ leaverequest.group.name }}</td>
                                                    <td class="text-right">
                                                        <a href="{% url 'groupmanagement:leave_accept_request' leaverequest.id %}" class="btn btn-success">
                                                            {% translate "Accept" %}
                                                        </a>

                                                        <a href="{% url 'groupmanagement:leave_reject_request' leaverequest.id %}" class="btn btn-danger">
                                                            {% translate "Reject" %}
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                                <div class="alert alert-warning text-center">{% translate "No group leave requests." %}</div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% translate "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'groupmanagement:management' %}">{% translate "Group Management" %}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'groupmanagement:management' %}">
                    <a href="{% url 'groupmanagement:management' %}">{% translate "Group Requests" %}</a>
                </li>
                <li class="{% navactive request 'groupmanagement:membership groupmanagement:audit_log' %}">
                    <a href="{% url 'groupmanagement:membership' %}">{% translate "Group Membership" %}</a>
                </li>
            </ul>
        </div>
    </div>
</nav>